
# image: gitpod/workspace-postgres:latest
image: axonasif/workspace-postgres:latest
#   file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # - init: echo 'init script' # runs during prebuild
  
  - command: |
      echo 'start script'
      gp open main.py
      python3 main.py

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
