image:
  file: .gitpod.Dockerfile

tasks:
  - name: Test installing pip package from prebuild env
    init: pip install bpytop
  # - name: Test using `pyenv install <>` from prebuild env (excluded this test because it takes a while during my development)
  #   init: pyenv install 3.9.0
  - name: cowsay
    command: cowsay Gitpod

github:
  prebuilds:
    branches: true
