tasks:
  - before: |
      _t="$HOME/hostname" && echo testname > "$_t"
      sudo nsenter -t 1 mount --bind "$_t" /proc/sys/kernel/hostname
      sudo nsenter -t 1 mount --bind "$_t" /etc/hostname

github:
  prebuilds:
    branches: true
