tasks:
  - name: combined tasks
    command: echo this is a command (combined)
    before: echo this is a before (combined)

  - command: echo this is a command but separate
  - before: echo this is a before but separate

github:
  prebuilds:
    branches: true
