github:
  prebuilds:
    branches: true
 
tasks:
  - before: gp ports visibility 3000:public # Doesn't work
    command: python3 -m http.server 3000
    
  - command: |
      # Doesn't work
      gp ports visibility 3000:public
      sleep 1
      gp ports visibility 3000:public
      sleep 1
      gp ports visibility 3000:public

ports:
  - name: random
    port: 3000
    onOpen: open-browser
    visibility: public
