image:
  file: .gitpod.Dockerfile
 
tasks:
  - init: cargo init . && exit
  - command: code src/main.rs && exit
github:
  prebuilds:
    branches: true

vscode:
  extensions:
    - rust-lang.rust
    - matklad.rust-analyzer
