image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Run discord
    command: discord

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
