image:
  file: .gitpod.Dockerfile

tasks:
  - init: cargo init --name rusttest . && exit
  - command: gp await-port 23000 && gp open src/main.rs && exit
github:
  prebuilds:
    branches: true

vscode:
  extensions:
    - rust-lang.rust
    - matklad.rust-analyzer
