workspaceLocation: bashbox
additionalRepositories:
  - url: https://github.com/axonasif/gearlock
    checkoutLocation: gearlock
  - url: https://github.com/bashbox/bashbox

image: gitpod/workspace-base
