image: gitpod/workspace-base

# We run the task commands in a subshell and exit the main shells, thus vscode is left with no open shells.
tasks:
  # Terminal 1
  - name: combined tasks
    command: |
      (
        echo "this is a command (combined)"
        cowsay Hello
        python3 -c "print('hi')"
      ) & disown # <- subshell background process

      exit # <- closes the vscode terminal tab
      
    before: |
      printf '%s\n' 'f=/tmp/.ok; if test ! -e $f; then touch $f; exit; fi' >> ~/.bashrc # To close the empty terminal Gitpod opens, once.

      echo "something" > .env && exit # <- closes the vscode terminal tab

  # Terminal 2
  - before: |
      (
        npm install
        cargo check
      ) & disown # <- subshell background process

      exit # <- closes the vscode terminal tab
        
github:
  prebuilds:
    branches: true
