tasks:
  - before: |
      for repo in /workspace/*/.git; do {
          if test "${repo} == "${GITPOD_REPO_ROOT}"; then continue; fi

          default_branch="$(git -C "${repo}" rev-parse --abbrev-ref origin/HEAD)"
          default_branch="${default_branch##*/}"
          current_branch="$(git -C "${repo}" rev-parse --abbrev-ref HEAD)

          if test "${current_branch}" != "${default_branch}"; then {
              git -C "${repo}" checkout "${default_branch}"
          } fi
      } done

      exit 0

additionalRepositories:
  - url: https://github.com/axonasif/gearlock
    checkoutLocation: gearlock
  - url: https://github.com/bashbox/bashbox

image: gitpod/workspace-base
