image: axonasif/workspace-full-vnc
github:
  prebuilds:
    branches: true

tasks:
  - name: Hello
    command: echo hello world
  - name: Foo
    command: echo Foo
  - name: Bar
    command: echo bar
