github:
  prebuilds:
    branches: true

tasks:
 - init: docker-compose build
 - name: Rails Server
 command: docker-compose up
 - name: Compile Extensions
 command: gp url 3000 > .gitpod-url && node build-extension.js
 openMode: split-right
ports:
 - port: 3000
 onOpen: open-browser
 visibility: public
