image: registry.hub.docker.com/githubactivity/workspace-full@sha256:72c3f1d720d8307c775036535ff2ca9709ce9fb86aabfb88784a64bb0cb5103a


tasks:
  - name: Hello
    command: echo hello world
  - name: Foo
    command: echo Foo
  - name: Bar
    command: echo bar
