image: gitpod/workspace-base

tasks:
  - init: |
      sleep 120
      if test ! -e /workspace/hey; then
        printf '%s/%s' "$(date)" "$GITPOD_INSTANCE_ID" > /workspace/hey
      fi
# 26806
# 469
# 11695
# 22491
# 2347
# 14329
# 11308
# 13878
# 5632
# 17054
# 2068
# 16713
# 28885
